//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UseWCF2.netTCPServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/WCFHost")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _chatContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _userNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _chatContent {
            get {
                return this._chatContentField;
            }
            set {
                if ((object.ReferenceEquals(this._chatContentField, value) != true)) {
                    this._chatContentField = value;
                    this.RaisePropertyChanged("_chatContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _userName {
            get {
                return this._userNameField;
            }
            set {
                if ((object.ReferenceEquals(this._userNameField, value) != true)) {
                    this._userNameField = value;
                    this.RaisePropertyChanged("_userName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="netTCPServiceReference.IService1", CallbackContract=typeof(UseWCF2.netTCPServiceReference.IService1Callback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        void Register(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendToOtherClients", ReplyAction="http://tempuri.org/IService1/SendToOtherClientsResponse")]
        void SendToOtherClients(UseWCF2.netTCPServiceReference.Person person, string specificClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFileList", ReplyAction="http://tempuri.org/IService1/GetFileListResponse")]
        System.Data.DataSet GetFileList(string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPic", ReplyAction="http://tempuri.org/IService1/GetPicResponse")]
        byte[] GetPic(string dilePath, string fileName, int offSet, int blockSize);
        
        // CODEGEN: Generating message contract since the wrapper name (DownloadFileRequest) of message DownloadFileRequest does not match the default value (DownloadFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DownloadFile", ReplyAction="http://tempuri.org/IService1/DownloadFileResponse")]
        UseWCF2.netTCPServiceReference.MyFileInfo DownloadFile(UseWCF2.netTCPServiceReference.DownloadFileRequest request);
        
        // CODEGEN: Generating message contract since the operation SendFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendFile", ReplyAction="http://tempuri.org/IService1/SendFileResponse")]
        UseWCF2.netTCPServiceReference.SendFileResponse SendFile(UseWCF2.netTCPServiceReference.MyFileInfo request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Callback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/SendMessage")]
        void SendMessage(UseWCF2.netTCPServiceReference.Person person, int contentType);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/UpdateUserList")]
        void UpdateUserList(string[] userList);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadFileRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string _fileName;
        
        public DownloadFileRequest() {
        }
        
        public DownloadFileRequest(string _fileName) {
            this._fileName = _fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyFileInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MyFileInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string _fileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long _fileSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream _stream;
        
        public MyFileInfo() {
        }
        
        public MyFileInfo(string _fileName, long _fileSize, System.IO.Stream _stream) {
            this._fileName = _fileName;
            this._fileSize = _fileSize;
            this._stream = _stream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFileResponse {
        
        public SendFileResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : UseWCF2.netTCPServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.DuplexClientBase<UseWCF2.netTCPServiceReference.IService1>, UseWCF2.netTCPServiceReference.IService1 {
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Register(string userName) {
            base.Channel.Register(userName);
        }
        
        public void SendToOtherClients(UseWCF2.netTCPServiceReference.Person person, string specificClient) {
            base.Channel.SendToOtherClients(person, specificClient);
        }
        
        public System.Data.DataSet GetFileList(string filePath) {
            return base.Channel.GetFileList(filePath);
        }
        
        public byte[] GetPic(string dilePath, string fileName, int offSet, int blockSize) {
            return base.Channel.GetPic(dilePath, fileName, offSet, blockSize);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UseWCF2.netTCPServiceReference.MyFileInfo UseWCF2.netTCPServiceReference.IService1.DownloadFile(UseWCF2.netTCPServiceReference.DownloadFileRequest request) {
            return base.Channel.DownloadFile(request);
        }
        
        public long DownloadFile(ref string _fileName, out System.IO.Stream _stream) {
            UseWCF2.netTCPServiceReference.DownloadFileRequest inValue = new UseWCF2.netTCPServiceReference.DownloadFileRequest();
            inValue._fileName = _fileName;
            UseWCF2.netTCPServiceReference.MyFileInfo retVal = ((UseWCF2.netTCPServiceReference.IService1)(this)).DownloadFile(inValue);
            _fileName = retVal._fileName;
            _stream = retVal._stream;
            return retVal._fileSize;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UseWCF2.netTCPServiceReference.SendFileResponse UseWCF2.netTCPServiceReference.IService1.SendFile(UseWCF2.netTCPServiceReference.MyFileInfo request) {
            return base.Channel.SendFile(request);
        }
        
        public void SendFile(string _fileName, long _fileSize, System.IO.Stream _stream) {
            UseWCF2.netTCPServiceReference.MyFileInfo inValue = new UseWCF2.netTCPServiceReference.MyFileInfo();
            inValue._fileName = _fileName;
            inValue._fileSize = _fileSize;
            inValue._stream = _stream;
            UseWCF2.netTCPServiceReference.SendFileResponse retVal = ((UseWCF2.netTCPServiceReference.IService1)(this)).SendFile(inValue);
        }
    }
}
