//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.netTCPServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="netTCPServiceReference.IService1", CallbackContract=typeof(WCFClient.netTCPServiceReference.IService1Callback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        void Register(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendToOtherClients", ReplyAction="http://tempuri.org/IService1/SendToOtherClientsResponse")]
        void SendToOtherClients(WCFService.Person person, string specificClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFileList", ReplyAction="http://tempuri.org/IService1/GetFileListResponse")]
        System.Data.DataSet GetFileList(string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPic", ReplyAction="http://tempuri.org/IService1/GetPicResponse")]
        byte[] GetPic(string dilePath, string fileName, int offSet, int blockSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReceiveFile", ReplyAction="http://tempuri.org/IService1/ReceiveFileResponse")]
        void ReceiveFile(WCFService.ClientFile clientFile, bool isChangeFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendFile", ReplyAction="http://tempuri.org/IService1/SendFileResponse")]
        void SendFile(string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Test", ReplyAction="http://tempuri.org/IService1/TestResponse")]
        void Test(string clientName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Callback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/SendMessage")]
        void SendMessage(WCFService.Person person, int contentType);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/UpdateUserList")]
        void UpdateUserList(string[] userList);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/UpdateDownloadFile")]
        void UpdateDownloadFile(WCFService.ServiceFile serviceFile, double currentProgress, bool isFirstTime);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/test")]
        void test();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCFClient.netTCPServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.DuplexClientBase<WCFClient.netTCPServiceReference.IService1>, WCFClient.netTCPServiceReference.IService1 {
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Register(string userName) {
            base.Channel.Register(userName);
        }
        
        public void SendToOtherClients(WCFService.Person person, string specificClient) {
            base.Channel.SendToOtherClients(person, specificClient);
        }
        
        public System.Data.DataSet GetFileList(string filePath) {
            return base.Channel.GetFileList(filePath);
        }
        
        public byte[] GetPic(string dilePath, string fileName, int offSet, int blockSize) {
            return base.Channel.GetPic(dilePath, fileName, offSet, blockSize);
        }
        
        public void ReceiveFile(WCFService.ClientFile clientFile, bool isChangeFileName) {
            base.Channel.ReceiveFile(clientFile, isChangeFileName);
        }
        
        public void SendFile(string clientName) {
            base.Channel.SendFile(clientName);
        }
        
        public void Test(string clientName) {
            base.Channel.Test(clientName);
        }
    }
}
